### ISSUE TITLE
Что это за задача?

### ISSUE THREAD

**Issue by coursar** [Zalyalov-Almaz/CashbackDeposit#1]

**Comment by Zalyalov-Almaz** [comment]
Добрый вечер, с 4 лекции, написать сервис с двумя методами Cashback и Deposit, на основании логики с предыдущей лекции Отправлено из приложения "Почта" для Windows 10 От: coursarОтправлено: 16 октября 2020 г. в 20:23Кому: Zalyalov-Almaz/CashbackDepositКопия: SubscribedТема: [Zalyalov-Almaz/CashbackDeposit] Что это за задача? (#1) —You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Zalyalov-Almaz** [comment]
Добрый вечер, с 4 лекции, написать сервис с двумя методами Cashback и Deposit, на основании логики с предыдущей лекции

**Comment by coursar** [comment]
Так а где `BankService` с двумя методами?
